beam:
  rest:
    swagger-open: true  #是否开启swagger (true/false)
    auth-open: false #jwt鉴权机制是否开启(true或者false)
    sign-open: false #签名机制是否开启(true或false)
    #file-upload-path: d:/tmp       #文件上传目录(不配置的话为java.io.tmpdir目录)
    file-upload-path: /upload/voice      #文件上传目录(不配置的话为java.io.tmpdir目录)
jwt:
  header: Authorization   #http请求头所需要的字段
  secret: hsshy        #jwt秘钥
  expiration: 604800      #7天 单位:秒
  auth-path: auth         #认证请求的路径
  md5-key: randomKey      #md5加密混淆key

spring:
  profiles:
    active: @spring.active@
#  flyway:
#    baseline-on-migrate: true


mybatis-plus:
  mapper-locations: classpath*:com/hsshy/beam/**/dao/mapping/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.hsshy.beam.*.entity

log:
  path: beam-logs
---

server:
   port: 8081
spring:
  profiles: local
  datasource:
      url: jdbc:mysql://119.29.192.127:3306/beam?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
      username: hsshy
      password: Hs!23456
      filters: log4j,wall,mergeStat

---

spring:
  profiles: dev
  datasource:
      url: jdbc:mysql://119.29.192.127:3306/beam?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
      username: hsshy
      password: Hs!23456
      filters: log4j,wall,mergeStat


---
beam:
  swagger-open: false              #是否开启swagger (true/false)

spring:
  profiles: produce
  datasource:
      url: jdbc:mysql://119.29.192.127:3306/beam?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
      username: hsshy
      password: Hs!23456
      filters: log4j,wall,mergeStat


