beam:
  swagger-open: true              #是否开启swagger (true/false)

jwt:
  header: Authorization   #http请求头所需要的字段
  secret: hsshy        #jwt秘钥
  expiration: 604800      #7天 单位:秒
  auth-path: auth         #认证请求的路径
  md5-key: randomKey      #md5加密混淆key

spring:
  profiles:
    active: @spring.active@
mybatis-plus:
  mapper-locations: classpath*:com/hsshy/beam/**/mapping/*.xml
  typeAliasesPackage: com.hsshy.beam.modular.*.entity
  global-config:
    id-type: 2  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用
---

server:
   port: 8081
spring:
  profiles: local
  datasource:
      url: jdbc:mysql://119.29.192.127:3306/beam_rest?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
      username: hsshy
      password: Hs!23456
      filters: log4j,wall,mergeStat
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create



---

spring:
  profiles: dev
  datasource:
      url: jdbc:mysql://119.29.192.127:3306/beam_rest?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
      username: hsshy
      password: Hs!23456
      filters: log4j,wall,mergeStat


---

spring:
  profiles: test
  datasource:
      url: jdbc:mysql://119.29.192.127:3306/beam_rest?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
      username: hsshy
      password: Hs!23456
      filters: log4j,wall,mergeStat


---
beam:
  swagger-open: false              #是否开启swagger (true/false)

spring:
  profiles: produce
  datasource:
      url: jdbc:mysql://119.29.192.127:3306/beam_rest?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
      username: hsshy
      password: Hs!23456
      filters: log4j,wall,mergeStat
