server:
   port: 8080

spring:
  profiles:
    active: @spring.active@


log:
  path: beam-logs
---

server:
  port: 8080
spring:
  thymeleaf:
    cache: false
  profiles: local
  datasource:
    url: jdbc:mysql://119.29.192.127:3306/beam?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
    username: hsshy
    password: Hs!23456
    filters: log4j,wall,mergeStat

---

spring:
  thymeleaf:
    cache: false
  profiles: dev
  datasource:
    url: jdbc:mysql://119.29.192.127:3306/beam?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
    username: hsshy
    password: Hs!23456
    filters: log4j,wall,mergeStat

---


spring:
  thymeleaf:
    cache: false
  profiles: produce
  datasource:
    url: jdbc:mysql://119.29.192.127:3306/beam?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
    username: hsshy
    password: Hs!23456
    filters: log4j,wall,mergeStat