#博客 https://www.jianshu.com/p/e1df915f0125
dubbo:
    application:
      id: dubbo-constomer
      name: dubbo-constomer
      qos-enable: true
      qos-port: 33333
    protocol:
      id: dubbo
      name: dubbo
      port: 20880
    registry:
      address: zookeeper://119.29.192.127:2181
      timeout: 100000
consumer:
  swagger-open: true  #是否开启swagger (true/false)
  auth-open: true #拦截器是否开启(true或者false)
  sign-open: true #签名机制是否开启(true或false)
  file-upload-path: /home/upload/data      #文件上传目录(不配置的话为java.io.tmpdir目录)
  version: 1.0.0

spring:
  profiles:
    active: @spring.active@
  application:
    name: dubbo-consumer

---


server:
  port: 7073
spring:
  profiles: local
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/beam?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    filters: log4j,wall,mergeStat
    hikari:
      readOnly: false
      connectionTimeout: 60000
      idleTimeout: 60000
      validationTimeout: 3000
      maxLifetime: 60000
      loginTimeout: 5
      maximumPoolSize: 60
      minimumIdle: 10
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:      # 密码（默认为空）
    timeout: 6000ms

---
dubbo:
  swagger-open: false

server:
  port: 7073
spring:
  profiles: produce
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/beam?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    filters: log4j,wall,mergeStat
    hikari:
      readOnly: false
      connectionTimeout: 60000
      idleTimeout: 60000
      validationTimeout: 3000
      maxLifetime: 60000
      loginTimeout: 5
      maximumPoolSize: 60
      minimumIdle: 10
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 6000ms



